### PR TITLE
Fix/clean/refactor is_loop_carried function and add new is_loop_independent function.

### PR DESCRIPTION
**Pull request by Haerezis**
Move around some code, remove now unnecessary piece of code (like useless precondition).
Fix and clean candl_dependence_is_loop_carried (the code checking if the dependence was loop-independent wasn't working).
Add a function called candl_dependence_is_loop_independent that check if a dependence is loop-independent using piplib.

### CODE REVIEW

**Comment by ftynse** [comment]
LGTM overall.

**Comment by Haerezis** [comment]
I just pushed a last commit because a closing parenthesis was missing :/ .

**Comment by Haerezis** [comment]
I've also talked to @Ced about the tests that you wanted to add.
He said that we should wait that we implement a parallelizer in candl, to check the parallelizer output.
Because he want to avoid another unitary test with a C program.

**Comment by ftynse** [comment]
Agreed.
It is easier to test that way.

**Comment by ftynse** [comment]
Test failure on bundled build, was not failing before.

```
check unitary/scalpriv [ FAIL ]
```

**Comment by Haerezis** [comment]
Ho.
I was testing using the tests produced by cmake (make test), but it seems that those are just valgrind check.

I'll try to see what's up (and maybe try to fix the cmake test to behave normaly).

**Comment by Haerezis** [comment]
I know where the problem is : I left a if enclosed return because I honestly didn't understood what it was doing...
When I remove it, it works again.
But I think that there something wrong with how is_loop_carried construct the linear system given to pip : I need to talk to @Ced about that to be sure.

**Comment by Haerezis** [comment]
A fix has been added. The tests are now successful.
I also fixed the cmake file to call the unitary tests instead of the
memory leak tests.

**Comment by ftynse** [comment]
This fix also fixes the problem in parallelism extractor.

I am okay to merge.

**Pull request merged**
